FROM python:3.9
# FROM nvidia/cuda:11.6.1-cudnn8-runtime-ubuntu20.04

WORKDIR /mxnet

# COPY ./sources.list /etc/apt/sources.list


ARG  DEBIAN_FRONTEND=noninteractive

RUN rm -f /etc/apt/sources.list.d/cuda.list \
    && rm -f /etc/apt/sources.list.d/nvidia-ml.list

COPY ./requirements.txt /mxnet/requirements.txt
RUN apt-get update && apt-get install -y \
    # python3 \
    # python3-pip \
    libopenblas-dev \
    libzmq3-dev \
    libopencv-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt


RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
